pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'shivamsinha2000/demo-app:latest'
    }

    stages {
        stage('Clone Repo') {
            steps {
                git branch: 'main', url: 'https://github.com/shivamsinha2000/demo_app.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    dockerImage = docker.build(DOCKER_IMAGE)
                }
            }
        }

        stage('Push to DockerHub') {
            steps {
                script {
                    docker.withRegistry('', 'dockerhub-creds') {
                        dockerImage.push()
                    }
                }
            }
        }

        stage('Deploy on EC2') {
            steps {
                sh '''
                docker stop flask_app || true
                docker rm flask_app || true
                docker pull $DOCKER_IMAGE
                docker run -d --name flask_app -p 5000:5000 $DOCKER_IMAGE
                '''
            }
        }
    }
}