pipeline {
    agent any
    
    environment {
        DOCKER_HUB_CREDENTIALS = credentials('dockerhub-id')
        EC2_SSH_KEY = credentials('ec2-ssh-key-id')
        EC2_IP = '54.197.139.136'
        EC2_USER = 'ubuntu'
    }
    
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/shivamsinha2000/demo_app.git'
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    dockerImage = docker.build("yourdockerhubusername/flask-app:${env.BUILD_ID}")
                }
            }
        }
        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com', 'dockerhub-id') {
                        dockerImage.push()
                    }
                }
            }
        }
        stage('Deploy to EC2') {
            steps {
                sshagent(['ec2-ssh-key-id']) {
                    sh "scp -o StrictHostKeyChecking=no docker-compose.yml ubuntu@${EC2_IP}:~/"
                    sh "ssh -o StrictHostKeyChecking=no ubuntu@${EC2_IP} 'bash ~/deploy.sh'"
                }
            }
        }
    }
}
